import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import "bootstrap/dist/css/bootstrap.min.css";

import Header from "../components/Header/page";
import Footer from "../components/Footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Z.PERSONAL",
    description: "Generated by 7V NGUYEN VU",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header></Header>
                {children}
                {/* <Footer></Footer> */}
            </body>
        </html>
    );
}
