import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import "bootstrap/dist/css/bootstrap.min.css";

import { GlobalContextProvider } from "@/context/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Z.PERSONAL",
    description: "Generated by 7V NGUYEN VU",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <GlobalContextProvider>{children}</GlobalContextProvider>
            </body>
        </html>
    );
}
